# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)+np.nan

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
array=np.array([1,2,3,4,5,6]) 
array.size*array.itemsize # array.itemsize will get the memory size of one item in the array (4 for int, 8 for float)

24

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
# help("numpy.add")
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a=np.zeros(10)+np.nan
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
r=np.array([1,2,3,4])
r[::-1]

array([4, 3, 2, 1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
ar=np.array([1,2,0,0,4,0])
np.nonzero(ar)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
np.random.RandomState(48).random((3,3,3))

array([[[0.01749027, 0.89157327, 0.28486117],
        [0.29897638, 0.79203426, 0.3244706 ],
        [0.86471039, 0.44751263, 0.54822991]],

       [[0.35717199, 0.11231203, 0.14189715],
        [0.44495908, 0.73198023, 0.46010123],
        [0.59274441, 0.33671386, 0.45442782]],

       [[0.18712777, 0.40883521, 0.13210204],
        [0.03711031, 0.08198783, 0.21343995],
        [0.54522926, 0.65506635, 0.58878792]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
m=np.random.RandomState(48).random(size=(10,10))
print(f"Min value : {m.min()}")
print(f"Max value : {m.max()}")

Min value : 0.0007973040569280165
Max value : 0.99175535046795


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
v=np.random.RandomState(48).random(30)
v.mean()

0.4080698217711573

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
q=np.ones((4,4))
q[1:len(q)-1,1:len(q)-1]=0
q

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
v=np.array([[1,2],[3,4]])
np.pad(v,1,mode="constant",constant_values=0)

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
#0 * np.nan -> nan
#np.nan == np.nan -> False
#np.inf > np.nan -> False
#np.nan - np.nan -> False
#np.nan in set([np.nan]) -> False
#0.3 == 3 * 0.1 -> False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
np.tile([[0,1],[1,0]],[4,4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [22]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
np.tile([[1,0],[0,1]],[4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:
print(r:=np.random.RandomState(43).randint(0,10,(5,5)))
#Formula of normal distribution : (1/2pi)*e^(-((x^2)/2))
np.exp(-((np.square(r))/2))/(2*np.pi)

[[4 0 1 5 0]
 [3 1 2 7 0]
 [3 2 9 1 2]
 [2 3 5 4 4]
 [0 5 8 0 0]]


array([[5.33905355e-05, 1.59154943e-01, 9.65323526e-02, 5.93115274e-07,
        1.59154943e-01],
       [1.76805171e-03, 9.65323526e-02, 2.15392793e-02, 3.64422619e-12,
        1.59154943e-01],
       [1.76805171e-03, 2.15392793e-02, 4.10103631e-19, 9.65323526e-02,
        2.15392793e-02],
       [2.15392793e-02, 1.76805171e-03, 5.93115274e-07, 5.33905355e-05,
        5.33905355e-05],
       [1.59154943e-01, 5.93115274e-07, 2.01556455e-15, 1.59154943e-01,
        1.59154943e-01]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
dtype=np.dtype([("r",float),("g",float),("b",float),("a",float)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
a=np.array([[4,6,2],[1,71,3],[12,7,8],[5,64,3],[21,19,8]])
b=np.array([[2,4],[1,6],[5,5]])
np.matmul(a,b)
np.dot(a,b)
np.einsum("ij,jr->ir",a,b)

array([[ 24,  62],
       [ 88, 445],
       [ 71, 130],
       [ 89, 419],
       [101, 238]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
w=np.random.RandomState(42).randint(10,size=8)
print(w)
w[(w>3)&(w<8)]-=1
w

[6 3 7 4 6 9 2 6]


array([5, 3, 6, 3, 5, 9, 2, 5])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
#The sum function in the first print statement is the builtin sum function in python which sums all elements 
#iterable and integers the result will be : 0+1+2+3+4-1 = 9 (first summing over range(5):0+1+2+3+4 then adding -1)

#After we import everything from numpy, the sum function is included and is called in the second print statement
#however this function takes two arguments: the iterable or range which in this case is range(5), and the 
#dimension to sum over which is -1 (equivalent to the first dimension.), meaning we are no longer adding -1 to the equation
#and the result is : 0+1+2+3+4 = 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
z=np.array([3])
z**z
2<<z>>2
z<-z
1j*z
z/1/1
z<z>z

array([False])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
# np.array(0)/np.array(0) -> nan
# np.array(0)//np.array(0) -> 0
# np.array([np.nan]).astype(int).astype(float) -> array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
r=np.random.RandomState(34).randn(20)
print(r)
np.where(r>0,np.ceil(r),np.floor(r))

[ 0.2438351  -0.74731818 -1.56117699 -0.46425312 -0.35206234 -1.28149188
  0.28929924  0.9800285   0.47792422  0.45081813  0.75244345 -0.51057179
 -0.70575214 -0.42431725 -0.23216213  1.81514048 -2.09474937  1.03595611
 -1.43414066 -0.2782287 ]


array([ 1., -1., -2., -1., -1., -2.,  1.,  1.,  1.,  1.,  1., -1., -1.,
       -1., -1.,  2., -3.,  2., -2., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
x=np.array([4,7,8,2,2])
y=np.array([3,9,4,2])
# x[np.isin(x,y,True)]
np.intersect1d(x,y)

array([2, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
with np.errstate(all="ignore"):
    print(np.array(0)/np.array(0))

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
# np.sqrt(-1) will return nan with a warning that we cannot square root negative values
# while np.emath.sqrt(-1) will return 1j as it will treat -1 as j^2
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\mcc.DESKTOP-470HVN8\AppData\Local\Temp\ipykernel_3316\2234558210.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
today=np.datetime64("today","D")
tomorrow=today+np.timedelta64(1)
yesterday=today-np.timedelta64(1)
print(f"Today is : {today}.")
print(f"Tomorrow is : {tomorrow}.")
print(f"Yesterday was : {yesterday}.")

Today is : 2024-09-27.
Tomorrow is : 2024-09-28.
Yesterday was : 2024-09-26.


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
np.arange("2016-07","2016-08",dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A=np.array([1,2,3],dtype=np.float32)
B=np.array([5,5,5],dtype=np.float32)
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)
A

array([ -3.,  -7., -12.], dtype=float32)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
k=np.array([2.6,6.8,3.4,1.2,8.7])

#method 1 : np.floor
np.floor(k)

#method 2 : type casting
k.astype(np.int8)

#method 3 : np.trunc
np.trunc(k)

#method 4 :  
k-k%1

array([2., 6., 3., 1., 8.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
np.tile(np.arange(5),[5,1])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generator_function():
        return [np.random.randint(10) for i in range(10)]
np.fromiter(generator_function(),dtype=np.int32)

array([4, 4, 2, 0, 8, 9, 0, 4, 5, 2])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
np.random.uniform(size=10)

array([0.36882207, 0.62402012, 0.83957296, 0.05071588, 0.96071738,
       0.89668445, 0.76857666, 0.78676366, 0.76234597, 0.37753426])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
print(v:=np.random.RandomState(45).random(size=10))
v.sort(kind="heapsort")
v

[0.98901151 0.54954473 0.2814473  0.07728957 0.4444695  0.47280797
 0.048522   0.16332445 0.11595071 0.62739168]


array([0.048522  , 0.07728957, 0.11595071, 0.16332445, 0.2814473 ,
       0.4444695 , 0.47280797, 0.54954473, 0.62739168, 0.98901151])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
np.add.reduce(np.array([1,2,3]),keepdims=False)

6

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A=np.array([1,4,2,6])
B=np.array([1,4,2,7])
np.allclose(A,B) #Allclose works with arrays of the same size only and checks for each index if the elements are equal

A=np.array([9,8,6,5])
B=np.array([9,8,6,5,4,3])
np.array_equal(A,B) #Array_equal compares the length of the arrays and then checks for the elements

False

#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
i=np.array([4,7,9])
i.setflags(write=False)
i[1]=0

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [128]:
print(q:=np.random.RandomState(48).randint(1,10,size=(10,2)))
r=np.sqrt(np.square(q[:,0])*np.square(q[:,1]))
o=np.arctan(q[:,1]/q[:,0])
q[:,0]=r
q[:,1]=o
q

[[1 4]
 [2 5]
 [1 1]
 [7 7]
 [3 1]
 [7 7]
 [1 8]
 [9 3]
 [3 6]
 [3 6]]


array([[ 4,  1],
       [10,  1],
       [ 1,  0],
       [49,  0],
       [ 3,  0],
       [49,  0],
       [ 8,  1],
       [27,  0],
       [18,  1],
       [18,  1]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [129]:
h=np.random.RandomState(32).random(10)
print(h)
h[h==h.max()]=0
h

[0.85888927 0.37271115 0.55512878 0.95565655 0.7366696  0.81620514
 0.10108656 0.92848807 0.60910917 0.59655344]


array([0.85888927, 0.37271115, 0.55512878, 0.        , 0.7366696 ,
       0.81620514, 0.10108656, 0.92848807, 0.60910917, 0.59655344])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [142]:
z=np.zeros([5,5],[("x",float),("y",float)])
z["x"],z["y"]=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [154]:
X=np.array([6,12,5,32,12])
Y=np.array([4,15,14,21,26])

C=1/np.subtract.outer(X,Y)
C

array([[ 0.5       , -0.11111111, -0.125     , -0.06666667, -0.05      ],
       [ 0.125     , -0.33333333, -0.5       , -0.11111111, -0.07142857],
       [ 1.        , -0.1       , -0.11111111, -0.0625    , -0.04761905],
       [ 0.03571429,  0.05882353,  0.05555556,  0.09090909,  0.16666667],
       [ 0.125     , -0.33333333, -0.5       , -0.11111111, -0.07142857]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [170]:
for int_ in [np.int8,np.int16,np.int32,np.int64]:
    print(np.iinfo(int_))
    print()

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------


Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------


Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------


Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------




In [173]:
for float_ in [np.float16,np.float32,np.float64]:
    print(np.finfo(float_))
    print()

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------


Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------


Machine parameters for float64
-

#### 49. How to print all the values of an array? (★★☆)

In [246]:
o=np.array([9.849,3.934,5,2])
# np.set_printoptions(2,5)
o

array([9.85, 3.93, 5.  , 2.  ])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [8]:
import numpy as np
p=np.random.RandomState(45).randint(100,size=20)
u=np.random.RandomState(45).uniform(100)
p[(p-u).argmin()]

3

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [16]:
d=np.dtype([("x",float),("y",float),("r",float),("g",float),("b",float)])
np.array([(4,6,234,234,6),(2,1,325,327,10)],dtype=d)

array([(4., 6., 234., 234.,  6.), (2., 1., 325., 327., 10.)],
      dtype=[('x', '<f8'), ('y', '<f8'), ('r', '<f8'), ('g', '<f8'), ('b', '<f8')])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [21]:
j=np.random.RandomState(42).randint(1,100,size=(100,2))
A,B=np.atleast_2d(j[:,0],j[:,1])
D=np.sqrt((A-A.T)**2 + (B-B.T)**2)
D.round(2)

array([[ 0.  , 42.54, 72.56, ..., 54.13, 68.96, 53.01],
       [42.54,  0.  , 68.68, ..., 12.17, 72.62, 11.66],
       [72.56, 68.68,  0.  , ..., 75.93, 12.53, 66.22],
       ...,
       [54.13, 12.17, 75.93, ...,  0.  , 81.3 , 10.  ],
       [68.96, 72.62, 12.53, ..., 81.3 ,  0.  , 72.07],
       [53.01, 11.66, 66.22, ..., 10.  , 72.07,  0.  ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [26]:
z=np.array([1,4,5],dtype=np.float32)
a=z.view(np.int32)
a.dtype

dtype('int32')

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [31]:
from io import StringIO
file=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")
np.genfromtxt(file,delimiter=",",dtype=np.int32)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [36]:
e=np.array([3,7,4,2,9])
for i,e in np.ndenumerate(e):
    print(i[0],end=", ")
    print(e)

0, 3
1, 7
2, 4
3, 2
4, 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [45]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt((x*x)+(y*y))
z=np.exp(-(d**2/2))
z

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [139]:
p=4
h=np.zeros((3,3))
h.put(np.random.choice(range(h.size),p,replace=False),values=2)
h

array([[0., 2., 0.],
       [0., 2., 0.],
       [2., 0., 2.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [159]:
print(o:=np.random.RandomState(43).uniform(1,20,size=(4,4)))
print(m:=o.mean(axis=1))
o-=m.reshape(-1,1)
o

[[ 3.18603676 12.57226425  3.53442832  5.57120278]
 [ 7.21564206 17.32361233 13.65571405 11.28208203]
 [ 1.55126266 14.94121763  8.50405035 16.23889525]
 [ 5.83400139  2.0808138  17.46632418  5.19955092]]
[ 6.21598303 12.36926262 10.30885647  7.64517257]


array([[-3.02994627,  6.35628122, -2.68155471, -0.64478025],
       [-5.15362056,  4.95434971,  1.28645143, -1.08718058],
       [-8.75759381,  4.63236115, -1.80480612,  5.93003878],
       [-1.81117118, -5.56435878,  9.82115161, -2.44562165]])

#### 59. How to sort an array by the nth column? (★★☆)

In [170]:
n=3
print(e:=np.random.RandomState(32).randint(-10,20,size=(5,3)))
e[e[:,n-1].argsort()]

[[13  1 -5]
 [12 18 14]
 [ 9 18 -3]
 [15 -7 -5]
 [ 0 -1 -6]]


array([[ 0, -1, -6],
       [13,  1, -5],
       [15, -7, -5],
       [ 9, 18, -3],
       [12, 18, 14]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [183]:
print(f:=np.array([[9,np.nan,4,3],[12,np.nan,4,6],[31,np.nan,16,np.nan],[19,np.nan,24,23]]))
np.isnan(f).all(axis=0).any()

[[ 9. nan  4.  3.]
 [12. nan  4.  6.]
 [31. nan 16. nan]
 [19. nan 24. 23.]]


True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [188]:
print(b:=np.random.RandomState(43).uniform(-10,10,size=20))
v=0.7
b[abs((b-v)).argmin()]

[-7.69890867  2.18133079 -7.33218072 -5.1882076  -3.45721888  7.18274982
  3.32180426  0.82324425 -9.41972351  4.67496593 -2.10099963  6.04094237
 -4.91157748 -8.86230127  7.33297282 -5.57942008 -1.90021104 -3.67807058
 -8.466746    6.86449388]


0.8232442456680751

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [202]:
A=np.random.randint(20,size=(1,3))
B=np.random.randint(20,size=(3,1))
print(A)
print(B)
it = np.nditer([A,B,None])
for x,y,z in it:
    z=x+y
    print(z)

[[ 6 17 12]]
[[ 9]
 [15]
 [19]]
15
26
21
21
32
27
25
36
31


#### 63. Create an array class that has a name attribute (★★☆)

In [203]:
class Namedarray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj=np.asarray(array).view(cls)
        obj.name=name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.name=getattr(obj,"name","no name")

o=Namedarray([3,5,7],"ages")
o.name

'ages'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [234]:
print(z:=np.ones(10))
print(i:=np.random.RandomState(32).randint(0,len(z),size=20))
print(p:=np.bincount(i,minlength=len(z)))
z+=p
# np.add.at(z,i,1)
z

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7 5 6 8 3 7 9 3 5 9 4 1 3 1 2 3 8 2 4 2]
[0 2 3 4 2 2 1 2 2 2]


array([1., 3., 4., 5., 3., 3., 2., 3., 3., 3.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [248]:
x=np.array([3,2,5,6,7])
i=np.random.RandomState(759).randint(0,len(x),len(x))
print(i)
f=np.bincount(i,x)
f

[0 4 1 4 0]


array([10.,  5.,  0.,  0.,  8.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [255]:
w,h=256,256
I=np.random.RandomState(34).randint(0,4,(w,h,3)).astype(np.ubyte)
Colors=np.unique(I.reshape(-1,3),axis=0)
len(Colors)

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [97]:
b=np.random.RandomState(34).randint(0,10,(2,2,2,2))
print(b)
b.sum(axis=(-2,-1))

[[[[1 9]
   [6 5]]

  [[4 3]
   [5 2]]]


 [[[9 8]
   [6 5]]

  [[6 4]
   [5 0]]]]


array([[21, 14],
       [28, 15]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [109]:
D=np.array([5,2,8,6,1])
print(S:=np.random.RandomState(42).randint(0,len(D),len(D)))
sum_=np.bincount(S,weights=D)
count_=np.bincount(S)
with np.errstate(all="ignore"):
    mean_=sum_/count_
mean_

[3 4 2 4 4]


array([nan, nan,  8.,  5.,  3.])

#### 69. How to get the diagonal of a dot product? (★★★)

In [112]:
print(v:=np.random.RandomState(42).randint(0,20,(3,3)))
print()
print(b:=np.random.RandomState(22).randint(0,20,(3,3)))
v.dot(b).diagonal()

[[ 6 19 14]
 [10  7  6]
 [18 10 10]]

[[ 4 12  0]
 [ 4  6 11]
 [ 8  4 18]]


array([212, 186, 290])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [118]:
v=np.array([1,2,3,4,5])
zn=3
z0=np.zeros(len(v)+(len(v)-1)*zn)
z0[::zn+1]=v
z0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [126]:
print(h:=np.random.RandomState(42).randint(0,10,(5,5,3)))
print()
print(r:=np.random.RandomState(32).randint(0,10,(5,5)))
np.multiply(h,r.reshape(5,5,1))

[[[6 3 7]
  [4 6 9]
  [2 6 7]
  [4 3 7]
  [7 2 5]]

 [[4 1 7]
  [5 1 4]
  [0 9 5]
  [8 0 9]
  [2 6 3]]

 [[8 2 4]
  [2 6 4]
  [8 6 1]
  [3 8 1]
  [9 8 9]]

 [[4 1 3]
  [6 7 2]
  [0 3 1]
  [7 3 1]
  [5 5 9]]

 [[3 5 1]
  [9 1 9]
  [3 7 6]
  [8 7 4]
  [1 4 7]]]

[[7 5 6 8 3]
 [7 9 3 5 9]
 [4 1 3 1 2]
 [3 8 2 4 2]
 [4 4 9 5 9]]


array([[[42, 21, 49],
        [20, 30, 45],
        [12, 36, 42],
        [32, 24, 56],
        [21,  6, 15]],

       [[28,  7, 49],
        [45,  9, 36],
        [ 0, 27, 15],
        [40,  0, 45],
        [18, 54, 27]],

       [[32,  8, 16],
        [ 2,  6,  4],
        [24, 18,  3],
        [ 3,  8,  1],
        [18, 16, 18]],

       [[12,  3,  9],
        [48, 56, 16],
        [ 0,  6,  2],
        [28, 12,  4],
        [10, 10, 18]],

       [[12, 20,  4],
        [36,  4, 36],
        [27, 63, 54],
        [40, 35, 20],
        [ 9, 36, 63]]])

#### 72. How to swap two rows of an array? (★★★)

In [136]:
print(t:=np.random.RandomState(42).randint(0,10,(7,5)))
t[[2,6]]=t[[6,2]]
t

[[6 3 7 4 6]
 [9 2 6 7 4]
 [3 7 7 2 5]
 [4 1 7 5 1]
 [4 0 9 5 8]
 [0 9 2 6 3]
 [8 2 4 2 6]]


array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [8, 2, 4, 2, 6],
       [4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3],
       [3, 7, 7, 2, 5]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [56]:
print(faces:=np.random.RandomState(42).randint(0,100,(10,3)))
p=faces.repeat(2,axis=1)
e=np.roll(p,shift=-1,axis=1)
e=e.reshape(len(e)*3,2)
e=e.view([("a",e.dtype),("b",e.dtype)])
np.unique(e)

[[51 92 14]
 [71 60 20]
 [82 86 74]
 [74 87 99]
 [23  2 21]
 [52  1 87]
 [29 37  1]
 [63 59 20]
 [32 75 57]
 [21 88 48]]


array([( 1, 29), ( 1, 87), ( 2, 21), (14, 51), (20, 63), (20, 71),
       (21, 23), (21, 88), (23,  2), (29, 37), (32, 75), (37,  1),
       (48, 21), (51, 92), (52,  1), (57, 32), (59, 20), (60, 20),
       (63, 59), (71, 60), (74, 82), (74, 87), (75, 57), (82, 86),
       (86, 74), (87, 52), (87, 99), (88, 48), (92, 14), (99, 74)],
      dtype=[('a', '<i4'), ('b', '<i4')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [68]:
C=np.arange(2,26,3)
# A=[]
# for i,e in np.ndenumerate(C):
#     A.extend([i[0]]*e)
# A=np.array(A)
# np.bincount(A)==C
A=np.repeat(np.arange(len(C)),C)
np.bincount(A)==C

array([ True,  True,  True,  True,  True,  True,  True,  True])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [46]:
E=np.array([4,6,7,9,2,3,12,8])
n=2
r=np.cumsum(E,dtype=float)
r[n:]-=r[:-n]
r[n-1:]/=n
print(r[n-1:])
from numpy.lib.stride_tricks import sliding_window_view
sliding_window_view(E,2).mean(axis=-1)

[ 5.   6.5  8.   5.5  2.5  7.5 10. ]


array([ 5. ,  6.5,  8. ,  5.5,  2.5,  7.5, 10. ])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [63]:
print(Z:=np.random.RandomState(42).randint(-5,26,14))
# Z2=[]
# n=2
# while n<len(Z):
#     Z2.append([Z[n-2],Z[n-1],Z[n]])
#     n+=1
# Z2
from numpy.lib import stride_tricks

stride_tricks.as_strided(Z,shape=(len(Z)-3+1,3),strides=(Z.strides[0],Z.strides[0]))
sliding_window_view(Z,3)

[ 1 14 23  9  5  2 23 15  1 20 13 17  5  5]


array([[ 1, 14, 23],
       [14, 23,  9],
       [23,  9,  5],
       [ 9,  5,  2],
       [ 5,  2, 23],
       [ 2, 23, 15],
       [23, 15,  1],
       [15,  1, 20],
       [ 1, 20, 13],
       [20, 13, 17],
       [13, 17,  5],
       [17,  5,  5]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [111]:
a=np.array(True)
np.logical_not(a,out=a)

b=np.array([0.3,-0.9])
np.negative(b,out=b)

array([-0.3,  0.9])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [135]:
P0 = np.random.RandomState(43).uniform(-10,10,(10,2))
P1 = np.random.RandomState(42).uniform(-10,10,(10,2))
p  = np.random.RandomState(43).uniform(-10,10,( 1,2))

M=P1-P0 # Subtract the 2 set of points
T=(M**2).sum(axis=1) # Square the difference and find the sum of the coordinates
U=-((P0[:,0]-p[...,0])*M[:,0]+(P0[:,1]-p[...,1])*M[:,1])/T
U=U.reshape(len(U),1)
D=P0+U*M-p
np.sqrt((D**2).sum(axis=1))

array([ 0.        ,  6.51267291,  2.93874516,  3.99776893,  2.41397565,
        5.81213235, 11.38858528,  8.57367859,  2.67420852,  1.88895591])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [138]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))

for pi in p:
    M=P1-P0 # Subtract the 2 set of points
    T=(M**2).sum(axis=1) # Square the difference and find the sum of the coordinates
    U=-((P0[:,0]-pi[...,0])*M[:,0]+(P0[:,1]-pi[...,1])*M[:,1])/T
    U=U.reshape(len(U),1)
    D=P0+U*M-pi
    print(np.sqrt((D**2).sum(axis=1)))

[ 7.31559533  1.82536705  2.50424473  2.54929463  5.65172618 13.49871496
  8.26543763 10.64417967  6.1395301   1.31845974]
[ 6.96281721 13.24614388  8.21108358 16.76321935  5.30881095  0.96152744
  1.29705143  2.54052723  5.91488915 10.46694844]
[ 5.58332586 12.01391907  6.57946146 15.37472869  3.89866576  0.73394276
  0.39641755  1.04092319  4.33827157  8.87662888]
[ 7.15345537 13.13409229  9.18862436 16.97430668  7.3237336   0.4817913
  3.4062566   3.03248473  6.65231651 11.25632329]
[ 7.08051283 13.56806698  7.77282566 16.86693594  4.03160759  2.11333856
  0.15008206  2.44984961  5.65047151 10.16526616]
[ 8.23057614  0.68574139  8.79909217  1.49522862  7.89860821  3.42782079
  6.08847085 13.61226707 10.78631907  6.3212682 ]
[ 8.82845235  2.86056939  5.13573304  1.00506273  2.06723692 12.09691578
  5.05530017 12.60757973  8.45033874  3.70034339]
[10.00926591  3.40292844  7.89722927  0.21830888  2.44290412  9.61525854
  0.68239643 14.40792781 10.7427811   6.09535405]
[3.44967255 2.368

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [154]:
def extract(array:np.ndarray,element:int):
    shape=7
    index=None
    for i,e in np.ndenumerate(array):
        if e == element:
            index=i[0]
            break
    if index>=np.floor(shape/2) and index<=len(array)-np.ceil(shape/2):
        return array[int(index-np.floor(shape/2)):int(index+np.ceil(shape/2))]
    elif index<np.floor(shape/2):
        return np.pad(array[:int(index+np.ceil(shape/2))],(int(np.floor(shape/2)-index),0))
    elif index>len(array)-np.ceil(shape/2):
        return np.pad(array[int(index-np.floor(shape/2)):],(0,int(np.floor(shape/2)-(len(array)-1-index))))
F=np.random.RandomState(45).randint(-21,43,15)
element=-18
print(F)
extract(F,14)

[-10   9 -18  39  11  10  40   0  14 -17  36  35  -6 -20  -7]


array([ 10,  40,   0,  14, -17,  36,  35])

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [155]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
sliding_window_view(Z,4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [47]:
j=np.array([[15,27,4],[24,42,16],[8,8,17]])
np.linalg.matrix_rank(j)

i=np.array([[3,2],[6,4]])
np.linalg.matrix_rank(i)

1

#### 83. How to find the most frequent value in an array?

In [56]:
print(k:=np.random.RandomState(32).randint(3,62,40))

from collections import Counter
Counter(k).most_common(1)[0][0]

#or
np.bincount(k).argmax()

[26 46  8 57 27 22 10 28  6 40 45 12  7 14 20  6  4 37 38 27 45 21 13 23
 53 39 39 60  8 60 41 16 14 14 59 29 32 55 32 29]


14

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [68]:
print(r:=np.random.RandomState(48).randint(-14,56,(10,10)))
i=1+(r.shape[0]-3)
j=1+(r.shape[1]-3)
stride_tricks.as_strided(r,shape=(i,j,3,3),strides=r.strides+r.strides)

[[-14  37  54  34  50  20  15  -8  17  32]
 [ 34  14  44   1  16  52   4  39   4   7]
 [ 11  20  13  46  20  31  28  35   7  -8]
 [ 33   2  23  -1   8  40  -2  12   8 -12]
 [ 47   7  -7  21  36  50  53 -11   1  18]
 [-12  35  29   0  43 -13   9  38 -12  51]
 [ 40 -11   7  45  41  54  46  32  35  43]
 [ 21   0  54  18   3  14   2  40  29  -5]
 [ -5  15  34  55  41  -8 -14  -2  21  49]
 [  7   3  24  35  -7  30  42   3  50 -14]]


array([[[[-14,  37,  54],
         [ 34,  14,  44],
         [ 11,  20,  13]],

        [[ 37,  54,  34],
         [ 14,  44,   1],
         [ 20,  13,  46]],

        [[ 54,  34,  50],
         [ 44,   1,  16],
         [ 13,  46,  20]],

        [[ 34,  50,  20],
         [  1,  16,  52],
         [ 46,  20,  31]],

        [[ 50,  20,  15],
         [ 16,  52,   4],
         [ 20,  31,  28]],

        [[ 20,  15,  -8],
         [ 52,   4,  39],
         [ 31,  28,  35]],

        [[ 15,  -8,  17],
         [  4,  39,   4],
         [ 28,  35,   7]],

        [[ -8,  17,  32],
         [ 39,   4,   7],
         [ 35,   7,  -8]]],


       [[[ 34,  14,  44],
         [ 11,  20,  13],
         [ 33,   2,  23]],

        [[ 14,  44,   1],
         [ 20,  13,  46],
         [  2,  23,  -1]],

        [[ 44,   1,  16],
         [ 13,  46,  20],
         [ 23,  -1,   8]],

        [[  1,  16,  52],
         [ 46,  20,  31],
         [ -1,   8,  40]],

        [[ 16,  52,   4],
         [ 2

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [82]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

Z=np.array([[4,7,8],[12,12,23],[21,2,1]])
A=Z+Z.T
A-=np.diag(Z.diagonal())
A.view(Symetric)

Symetric([[ 4, 19, 29],
          [19, 12, 25],
          [29, 25,  1]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
n=3
p=4
print(A:=np.random.RandomState(43).randint(0,200,(p,n,n)))
print(B:=np.random.RandomState(43).randint(0,200,(p,n,1)))

[[[ 68  64  49]
  [ 21  58  16]
  [ 51 145 187]]

 [[ 91 194 110]
  [158  87  64]
  [ 35 127 178]]

 [[123  89 193]
  [111  34  75]
  [194 117 132]]

 [[ 36 117 175]
  [ 32  60 112]
  [ 73 162  48]]]
[[[ 68]
  [ 64]
  [ 49]]

 [[ 21]
  [ 58]
  [ 16]]

 [[ 51]
  [145]
  [187]]

 [[ 91]
  [194]
  [110]]]


In [90]:
np.tensordot(A,B,axes=[[0,2],[0,1]])

array([[126537],
       [ 66800],
       [127754]])

In [96]:
(A@B).sum(axis=0)

array([[126537],
       [ 66800],
       [127754]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [97]:
print(C:=np.random.RandomState(32).randint(3,51,(16,16)))

[[26 46  8 27 22 10 28  6 40 45 12  7 14 20  6  4]
 [37 38 27 45 21 13 23 39 39  8 41 16 14 14 29 32]
 [32 29 50  3 14  9 49 33  7 44 33 19 22 40 13 38]
 [48 27 50 14 32 50 46 14 37 44 46  7 31 23 21 20]
 [37 19 21 17 28  9 17 34  3 47 17 44 18  4 17 22]
 [36 15 10 43 17  9  9 45 37 43 20 39 11 28 12 21]
 [20 34 21 35  7  3 10  3 33 38 21 23 11  5 40 11]
 [17 31 28 21 46 22  9  8 33 36  9 18 46  4 50  3]
 [32 39 44 41 22 33 10 48 44 41  9  3 28 36 39 19]
 [16 15  6 16 40 13 50  7 41  8 43 12 13 23 43 34]
 [ 3 43 33 39 25 18 17 38 13 36 12 13 39 22 40 18]
 [37 38 40 39 25 16 50 12 33 25 41 42  7  3 19 13]
 [32 18 29 24 44 25 35 40 31 27 11 35 37 30 46  7]
 [39 24 50 27 32 35  5 18 49 19  5  4 43 42 21 50]
 [28 27  3 43 30  8 50 33 35 49 25 36 37 15  6 25]
 [29 45 33 16 26 23 10  3  7 16 18 35  5  9 36 48]]


In [119]:
stride_tricks.as_strided(C,(13,13,4,4),strides=C.strides+C.strides).sum(axis=(2,3))

array([[507, 453, 395, 406, 409, 443, 502, 488, 445, 403, 359, 296, 341],
       [494, 435, 403, 390, 431, 422, 484, 486, 452, 451, 389, 332, 358],
       [451, 389, 376, 366, 415, 408, 509, 504, 487, 485, 402, 349, 341],
       [447, 390, 366, 346, 333, 359, 460, 482, 499, 460, 348, 334, 295],
       [405, 393, 337, 302, 276, 284, 405, 427, 461, 441, 318, 370, 303],
       [467, 454, 402, 337, 301, 356, 447, 468, 447, 396, 311, 393, 364],
       [416, 446, 398, 378, 331, 367, 419, 422, 412, 359, 304, 394, 405],
       [424, 489, 447, 422, 406, 404, 439, 426, 371, 366, 330, 429, 457],
       [481, 505, 450, 454, 424, 443, 473, 451, 416, 372, 346, 382, 396],
       [428, 474, 432, 476, 455, 439, 463, 418, 423, 401, 383, 424, 394],
       [515, 530, 501, 456, 435, 435, 448, 410, 396, 396, 386, 443, 437],
       [498, 493, 470, 488, 458, 475, 511, 453, 467, 443, 413, 423, 401],
       [467, 471, 448, 433, 417, 407, 427, 386, 402, 402, 387, 437, 457]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [53]:
def iterator(a):
    p=(a[0:-2,0:-2]+a[0:-2,1:-1]+a[0:-2,2:]+
       a[1:-1,0:-2]+a[1:-1,2:]+
       a[2:,0:-2]+a[2:,1:-1]+a[2:,2:])

    birth = (p==3) & (a[1:-1,1:-1]==0)
    survive = ((p==2)|(p==3)) & (a[1:-1,1:-1]==1)
    a[...]=0
    a[1:-1,1:-1][birth|survive]=1
    return a

a=np.random.randint(0,2,(10,10))
for i in range(10):
    a=iterator(a)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 0 0 1 0]
 [0 0 0 0 1 1 0 1 1 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [79]:
n=4
h=np.array([3,12,1,5,
            21,43,22,20,
            17,18,13,11,
            6,41,81,2])
h[np.argpartition(-h,n)[:n]]

array([43, 41, 81, 22])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [97]:
a=np.array([6,3,9])
b=np.array([12,7,3])
c=np.array([32,87,1])

s=a.size*b.size*c.size
cartesian_product=np.array([(0,0,0) for i in range(s)])
for i,e in np.ndenumerate(a):
    i=i[0]
    for j,m in np.ndenumerate(b):
        j=j[0]
        for k,n in np.ndenumerate(c):
            k=k[0]
            p=int(i*9+j*3+k)
            cartesian_product[p]=(e,m,n)
cartesian_product

array([[ 6, 12, 32],
       [ 6, 12, 87],
       [ 6, 12,  1],
       [ 6,  7, 32],
       [ 6,  7, 87],
       [ 6,  7,  1],
       [ 6,  3, 32],
       [ 6,  3, 87],
       [ 6,  3,  1],
       [ 3, 12, 32],
       [ 3, 12, 87],
       [ 3, 12,  1],
       [ 3,  7, 32],
       [ 3,  7, 87],
       [ 3,  7,  1],
       [ 3,  3, 32],
       [ 3,  3, 87],
       [ 3,  3,  1],
       [ 9, 12, 32],
       [ 9, 12, 87],
       [ 9, 12,  1],
       [ 9,  7, 32],
       [ 9,  7, 87],
       [ 9,  7,  1],
       [ 9,  3, 32],
       [ 9,  3, 87],
       [ 9,  3,  1]])

#### 91. How to create a record array from a regular array? (★★★)

In [105]:
z=np.array([["Kyle",2.7,1],["Reese",5.5,3]])
r=np.core.records.fromarrays(z.T,names=["col1","col2","col3"],formats=["S8","f8","i8"])
r

rec.array([(b'Kyle', 2.7, 1), (b'Reese', 5.5, 3)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [111]:
Z=np.random.RandomState(32).randint(-30,45,300)
print(Z[:10])

#method 1 : double asterisks.
Z**3

#method 2 : np.power
np.power(Z,3)

#method 3 : multiply Z three times
Z*Z*Z

[ 13 -25  24  32 -11  41 -27 -21 -26 -19]


array([  2197, -15625,  13824,  32768,  -1331,  68921, -19683,  -9261,
       -17576,  -6859, -19683,  42875,     64,    125,   -216,   1728,
        -8000,   8000,  19683,  59319,    512,  -6859,  32768,  -6859,
           -1,  10648,  39304,  -6859, -13824,  54872,  32768,      0,
         8000,  85184,    125,  29791,   8000,   3375,   -216,  -6859,
         4913,   2197,   8000,  54872,   5832,  24389,  -1728,   -125,
        64000,  -4096,  29791,  21952,   9261,      1, -27000,  12167,
       -24389,  -4096,  -1331,  24389, -12167,  64000,  64000,   1000,
        -2197,  74088,  -9261,      8,  54872, -27000,  68921,  39304,
        74088,  46656,    343, -10648,  24389,  27000,  32768,   6859,
         5832,   2197,  64000,  59319,  35937, -13824,  -3375,   5832,
       -24389,   4913, -27000,  35937,    216,  24389,  32768,   5832,
        12167,  -1331,      0, -12167,   3375,   1331,    512,  21952,
        15625, -13824, -27000,  -2744,  35937,  -4913,  -5832,  50653,
      

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [143]:
print(A:=np.random.RandomState(32).randint(-10,10,(8,3)))
print(B:=np.random.RandomState(34).randint(-10,10,(2,2)))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
rows

[[ 1 -5  9]
 [-3 -7 -5]
 [ 0 -1 -6]
 [ 1  7 -7]
 [-9 -8 -7]
 [ 0  8  0]
 [ 8 -6 -6]
 [-5 -4  3]]
[[-9  0]
 [-1 -6]]


array([2], dtype=int64)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [151]:
print(P:=np.random.RandomState(43).randint(2,4,(10,3)))
z=np.all(P[:,1:]==P[:,:-1],axis=1)
P[~z]

[[2 2 3]
 [3 3 2]
 [2 3 3]
 [3 3 2]
 [2 2 3]
 [2 3 3]
 [2 3 3]
 [3 3 3]
 [2 3 2]
 [3 3 2]]


array([[2, 2, 3],
       [3, 3, 2],
       [2, 3, 3],
       [3, 3, 2],
       [2, 2, 3],
       [2, 3, 3],
       [2, 3, 3],
       [2, 3, 2],
       [3, 3, 2]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [156]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [162]:
O=np.array([[0,1,2],[0,1,2],[4,4,4]])
np.unique(O,axis=0)

array([[0, 1, 2],
       [4, 4, 4]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [194]:
A=np.array([6,8,2,3])
B=np.array([3,8,2,5])

np.einsum("i,i",A,B) #inner

np.einsum("i,j",A,B) #outer

np.einsum("i->",A) #sum

np.einsum("i,i->i",A,B) #multiply

array([18, 64,  4, 15])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [8]:
import numpy as np
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

array([ 0.00000000e+00, -3.73131229e-01, -2.59817608e+00, -3.26212050e+00,
       -2.18442687e+00, -2.98929946e-02,  2.42923642e+00,  4.54913599e+00,
        5.92318348e+00,  6.35117933e+00,  5.82369277e+00,  4.46259540e+00,
        2.47320794e+00,  1.09577220e-01, -2.36575300e+00, -4.71261671e+00,
       -6.72701769e+00, -8.25541575e+00, -9.18486120e+00, -9.46381505e+00,
       -9.11085788e+00, -8.12875279e+00, -6.63306046e+00, -4.69271059e+00,
       -2.44736165e+00, -2.05444585e-02,  2.46101146e+00,  4.86841760e+00,
        7.08937968e+00,  9.02539126e+00,  1.05948609e+01,  1.17357250e+01,
        1.24068974e+01,  1.25885805e+01,  1.22815267e+01,  1.15053927e+01,
        1.02963689e+01,  8.70429550e+00,  6.78948686e+00,  4.61716636e+00,
        2.25853448e+00, -1.98731680e-01, -2.68040566e+00, -5.11543300e+00,
       -7.41973991e+00, -9.53891040e+00, -1.14237629e+01, -1.29919305e+01,
       -1.42355069e+01, -1.51243232e+01, -1.56061571e+01, -1.57219415e+01,
       -1.54217066e+01, -

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [9]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [10]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.25775825  0.15294656]
